# Generated by Django 3.0.3 on 2020-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmpl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
